# 2024/01/07

potential-bugs:
  active: true
  AvoidReferentialEquality:
    active: false
  CastToNullableType:
    active: true
  Deprecation:
    active: true
  DontDowncastCollectionTypes:
    active: true
  DoubleMutabilityForCollection:
    active: true
    mutableTypes: [
      'kotlin.collections.MutableList',
      'kotlin.collections.MutableMap',
      'kotlin.collections.MutableSet',
      'java.util.ArrayList',
      'java.util.LinkedHashSet',
      'java.util.HashSet',
      'java.util.LinkedHashMap',
      'java.util.HashMap'
    ]
  ElseCaseInsteadOfExhaustiveWhen:
    active: false
  EqualsAlwaysReturnsTrueOrFalse:
    active: true
  EqualsWithHashCodeExist:
    active: true
  ExitOutsideMain:
    active: true
  ExplicitGarbageCollectionCall:
    active: true
  HasPlatformType:
    active: true
  IgnoredReturnValue:
    active: true
    restrictToConfig: false
    ignoreFunctionCall: [
      java.io.File.delete,
      java.lang.StringBuilder.append,
      java.util.concurrent.atomic.AtomicReference.compareAndSet,
      kotlin.TODO,
      kotlin.also,
      kotlin.checkNotNull,
      kotlin.collections.MutableList.add,
      kotlin.collections.MutableMap.remove,
      kotlin.collections.MutableSet.add,
      kotlin.collections.MutableSet.addAll,
      kotlin.collections.removeAll,
      kotlin.error,
      kotlinx.coroutines.flow.SharedFlow.collect,
      kotlinx.coroutines.launch,
      kotlinx.coroutines.withContext,
      org.junit.jupiter.api.Assertions.assertThrows
    ]
  ImplicitDefaultLocale:
    active: true
  ImplicitUnitReturnType:
    active: true
  InvalidRange:
    active: true
  IteratorHasNextCallsNextMethod:
    active: true
  IteratorNotThrowingNoSuchElementException:
    active: true
  LateinitUsage:
    active: true
    ignoreAnnotated: []
    ignoreOnClassesPattern: ''
  MapGetWithNotNullAssertionOperator:
    active: true
  MissingPackageDeclaration:
    active: true
  NullCheckOnMutableProperty:
    active: true
  NullableToStringCall:
    active: true
  PropertyUsedBeforeDeclaration:
    active: true
  UnconditionalJumpStatementInLoop:
    active: true
  UnnecessaryNotNullCheck:
    active: true
  UnnecessaryNotNullOperator:
    active: true
  UnnecessarySafeCall:
    active: true
  UnreachableCatchBlock:
    active: true
  UnreachableCode:
    active: true
  UnsafeCallOnNullableType:
    active: true
  UnsafeCast:
    active: true
  UnusedUnaryOperator:
    active: true
  UselessPostfixExpression:
    active: true # todo https://github.com/detekt/detekt/issues/4617
  WrongEqualsTypeParameter:
    active: true
